steps:

- name: 'alpine'
  args: ['sh', '-c', 'date -u +%Y%m%dT%H%M%S > /workspace/_TAG']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: ['-c', 'docker build -t us.gcr.io/apibin/apibin:$(cat /workspace/_TAG) -t us.gcr.io/apibin/apibin:latest .']

images: ['us.gcr.io/apibin/apibin']