steps:

- name: 'alpine'
  args: ['sh', '-c', 'date -u +%Y%m%dT%H%M%S > /workspace/_TAG']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: ['-c', 'docker build -t us.gcr.io/apibin/apibin:$(cat /workspace/_TAG) -t us.gcr.io/apibin/apibin:latest .']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'apibin', '--image', 'gcr.io/apibin/apibin', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images: ['us.gcr.io/apibin/apibin']